# Generated by Django 2.0.1 on 2019-03-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_deprt', models.CharField(max_length=20)),
                ('emp_porject', models.CharField(max_length=50)),
                ('emp_mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
